/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "content": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "database": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "main": {
      "type": "sst.aws.Router"
      "url": string
    }
    "web": {
      "type": "sst.aws.Nuxt"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}