/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "content": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "database": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "dsql": {
      "endpoint": string
      "region": string
      "type": "sst.aws.Dsql"
    }
    "main": {
      "type": "sst.aws.Router"
      "url": string
    }
    "resource-processor": {
      "name": string
      "type": "sst.aws.Function"
    }
    "web": {
      "type": "sst.aws.Nuxt"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}