#!/usr/bin/env bash
# fix-migration.sh
# Applies Aurora DSQL dialect fixes to a Drizzle migration SQL file.
# Usage: bash fix-migration.sh <path-to-migration.sql>

set -euo pipefail

FILE="${1:-}"

if [[ -z "$FILE" ]]; then
  echo "Usage: fix-migration.sh <path-to-migration.sql>" >&2
  exit 1
fi

if [[ ! -f "$FILE" ]]; then
  echo "File not found: $FILE" >&2
  exit 1
fi

echo "Fixing $FILE for Aurora DSQL..."

# 1. Remove USING <method> from CREATE INDEX (not supported)
sed -i '' 's/ USING [a-zA-Z_]*//' "$FILE"

# 2. Replace SERIAL with BIGINT GENERATED BY DEFAULT AS IDENTITY (CACHE 1)
sed -i '' 's/\bSERIAL\b/BIGINT GENERATED BY DEFAULT AS IDENTITY (CACHE 1)/g' "$FILE"

# 3. Replace BIGSERIAL with BIGINT GENERATED BY DEFAULT AS IDENTITY (CACHE 1)
sed -i '' 's/\bBIGSERIAL\b/BIGINT GENERATED BY DEFAULT AS IDENTITY (CACHE 1)/g' "$FILE"

# 4. Add IF NOT EXISTS to CREATE TABLE (idempotency)
sed -i '' 's/CREATE TABLE \([^I]\)/CREATE TABLE IF NOT EXISTS \1/g' "$FILE"

# 5. Add ASYNC IF NOT EXISTS to CREATE INDEX (idempotency + DSQL async indexing)
sed -i '' 's/CREATE INDEX \([^AUI]\)/CREATE INDEX ASYNC IF NOT EXISTS \1/g' "$FILE"

echo "Done."
