/**
 * Custom migrator for Aurora DSQL.
 * Drizzle's built-in migrator uses `SERIAL PRIMARY KEY` for its tracking table,
 * which Aurora DSQL does not support. This migrator replaces it with
 * `INTEGER GENERATED BY DEFAULT AS IDENTITY`.
 */

import fs from 'node:fs';
import path from 'node:path';
import type { AppDb } from './index';
import { sql } from 'drizzle-orm';

interface JournalEntry {
  idx: number;
  tag: string;
  when: number;
}

interface Journal {
  entries: JournalEntry[];
}

export async function dsqlMigrate(db: AppDb, migrationsFolder: string): Promise<void> {
  const journalPath = path.join(migrationsFolder, 'meta', '_journal.json');
  const journal: Journal = JSON.parse(fs.readFileSync(journalPath, 'utf-8'));

  // Create tracking table using DSQL-compatible syntax (no SERIAL).
  // Aurora DSQL requires CACHE >= 65536 or CACHE 1 for identity columns.
  await db.execute(sql`
    CREATE TABLE IF NOT EXISTS "__drizzle_migrations" (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY (CACHE 1) PRIMARY KEY,
      hash TEXT NOT NULL,
      created_at BIGINT
    )
  `);

  // Fetch already-applied migrations
  const applied = await db.execute<{ hash: string }>(sql`
    SELECT hash FROM "__drizzle_migrations"
  `);
  const appliedHashes = new Set(applied.rows.map((r) => r.hash));

  // Apply pending migrations in order
  for (const entry of journal.entries) {
    const sqlFile = path.join(migrationsFolder, `${entry.tag}.sql`);
    const content = fs.readFileSync(sqlFile, 'utf-8');
    const hash = entry.tag;

    if (appliedHashes.has(hash)) {
      console.log(`  Skipping already-applied migration: ${entry.tag}`);
      continue;
    }

    console.log(`  Applying migration: ${entry.tag}`);

    // Split on Drizzle breakpoint comments and run each statement
    const statements = content
      .split('--> statement-breakpoint')
      .map((s) => s.trim())
      .filter(Boolean);

    for (const statement of statements) {
      await db.execute(sql.raw(statement));
    }

    await db.execute(sql`
      INSERT INTO "__drizzle_migrations" (hash, created_at)
      VALUES (${hash}, ${Date.now()})
    `);

    console.log(`  Applied: ${entry.tag}`);
  }
}
